[package]
name = "zhlint-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.10.4"
unicode-width = "0.1.12"
lazy_static = "1.5.0"
